version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: invoice_db
    ports:
      - "5432:5432"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
